### PR TITLE
expose CommitDate, too

### PR DESCRIPTION
**Pull request by stapelberg**
When amending commits, the CommitDate gets updated, but AuthorDate does not.

For my website, I would like to use CommitDate as “last updated” instead of
AuthorDate.

### CODE REVIEW

**Comment by bep** [comment]
Could you amend one of the testfiles and add the `CommitDate` to the test assertions?

**Comment by stapelberg** [comment]
> Could you amend one of the testfiles and add the `CommitDate` to the test assertions?

Done.

**Comment by bep** [comment]
That looks good. I know there isn't a commit message guideline in this repo, and since this has to be a multi-commit PR, I cannot easily fix it myself-

The existing history should give you a guide:

* Commit message title is a proper  sentence starting with a capital letter, I suggest "Expose CommitDate"
* The only prefixing I do is packages, which isn't applicable here. If you do test commits, tell it in prose, e.g.: "Verify CommitDate in test"

**Comment by stapelberg** [comment]
Done.

**Comment by bep** [comment]
This may sound nitpicky, but I still see a commit message that starts with "add a ..."

**Comment by stapelberg** [comment]
Done.

**Pull request merged**
