### PR TITLE
Fix improper handling of file paths with bytes > 0x80

### PR DESCRIPTION
**Pull request by slnc**
Git log's default behavior is to quote strings with special characters but that isn't what gitmap's clients like Hugo expect so when they interact with gitmap, they send unquoted file paths and get no git info (see https://github.com/gohugoio/hugo/issues/9810 for an example).

h/t @jmooring for the fix and @bep for the help, I just packaged their ideas into this pull request.

### CODE REVIEW

**Review by slnc — COMMENTED** [review]
If I don't add the showSignatures bit I get a merge conflict with bep:master warning, but I can't figure out where it's coming from. It's my first github pull request, sorry if I'm doing something dumb.

**Comment by jmooring** [comment]
I'm not sure what you did, but the typical PR workflow is:

1. Fork on GitHub
2. Clone locally
3. Create new branch
4. Make changes
5. Test, test, test
6. Commit changes to your new branch
7. Push your new branch to your fork (origin)
8. Create PR from the new branch on your fork

**Comment by slnc** [comment]
> 

I missed the creating a new branch part, sorry, I'm going to redo the PR, thanks.

Another basic question: how do you run the existing gitmap_test.go tests with the current Go version (1.18.1)? I can't get it to run unless I create a go.mod file and then run `go test -v gitmap`.

Thanks

**Comment by jmooring** [comment]
I'm not sure why this module doesn't have go.mod/sum files. Maybe it was created before Go Modules was a thing.
Need guidance from @bep on this.

**Comment by slnc** [comment]
Will tentatively send the PR with a mod.go in it.

**Pull request closed without merging**
